name: ${project.name}
version: ${project.version}
description: Simple slapping plugin for players to abuse each other with
depend: []
softdepend: [VanishNoPacket]
author: Stealth2800
website: http://stealthyone.com/bukkit
main: com.stealthyone.mcb.simpleslap.SimpleSlap
commands:
  simpleslap:
    aliases: []
  slap:
    aliases: []