name: ${project.name}
version: ${project.version}
description: Slapping plugin for players to abuse each other with
depend: []
softdepend: [VanishNoPacket]
author: Stealth2800
website: http://stealthyone.com/bukkit
main: com.stealthyone.mcb.powerslap.PowerSlap
commands:
  powerslap:
    aliases: []
  slap:
    aliases: []